name: Bump Version

on:
  release:
    types: [ published ]
  workflow_dispatch:
    inputs: {}

jobs:
  bump-version:

    name: Bump version and update changelog
    runs-on: ubuntu-latest

    steps:
    # Setup environment
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    # Setup cache
    - name: Setup cache for Gradle and dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: "gradle-\
          ${{runner.os}}-\
          ${{hashFiles('gradle/wrapper/gradle-wrapper.properties')}}-\
          ${{hashFiles('**/*.gradle.kts')}}"
    # Build and publish
    - name: Update files
      run: ./gradlew --stacktrace patchChangelog
    # Commit and push files
    - name: Commit files
      run: |
        git -c user.name='GitHub Action' -c user.email='action@github.com' \
          commit -am "Bump version after releasing ${{ github.event.release.name }}"
    - name: Push changes
      run: |
        git push origin 'HEAD:${{ github.event.release.target_commitish }}'
